version: '3'
networks:
  common_networks:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    networks:
      common_networks:
        ipv4_address: 172.20.0.7
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mydb: 
          
  exam:
    image: plament/exam
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 && sleep 5 && echo "App is running on http://localhost:8000""
    ports:
      - 8000:8000
    networks:
      common_networks:
        ipv4_address: 172.20.0.6
    depends_on:
      db:
        condition: service_healthy
  volulmes:
    mydb:
      external:true